### ISSUE TITLE
Release a new version with rclone 1.54

### ISSUE THREAD

**Issue by ValentinB10** [wunderio/csi-rclone#19]
The version of rclone is set to to 1.53.
Could you update to the newest version of rclone to use the newest features of rclone and take advantage of recent bug fixes?

https://rclone.org/changelog/

PS: Your work on csi-rclone is amazing and it's extremely useful for my Kubernetes cluster. Thank you for this job.

**Comment by Jancis** [comment]
Latest image (v1.2.9) shipped with rclone 1.57.0
Related commit: https://github.com/wunderio/csi-rclone/commit/cbe4ebb5ca359561c50cb648373250ef97794ce1
