### ISSUE TITLE
question - OpenDrive?

### ISSUE THREAD

**Issue by ellitedev** [wunderio/csi-rclone#22]
This is probably a stupid question, but I couldn't really find an answer. Would it be possible to use this together with OpenDrive instead of MinIO? And if so, how?

**Comment by Jancis** [comment]
As long as it's supported by rclone, it should work.
You need to provide opendrive parameters like `--opendrive-username` and `--opendrive-password` in the rclone secret stringData (see `s3-access-key-id` in readme file)
See: https://rclone.org/opendrive/
