### ISSUE TITLE
The PVC in the example throws an error

### ISSUE THREAD

**Issue by blecx** [wunderio/csi-rclone#25]
Hello,

I just followd the example description. Installed a minio S3 and configured it. But the PVC stays in pending mode:

So here is what I've done

```bash
kubectl apply -f example/kubernetes/nginx-example.yaml
kubectl get pv | grep data-rclone-example
```
So the output of the pv seems to be fine.
```log
data-rclone-example                        1Gi        RWX            Retain           Available                                                         rclone                      6m58s
```
Then looking at the PVC

```bash
kubectl get pvc | grep data-rclone-example
```
So this keeps pending
```log
data-rclone-example                 Pending                                                                        rclone             9m4s
```
So let's look at the reason:
```bash
kubectl describe pvc data-rclone-example
```
So here is see and error that I don't understand
```log
Name:          data-rclone-example
Namespace:     default
StorageClass:  rclone
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       nginx-example
Events:
  Type     Reason              Age                   From                         Message
  ----     ------              ----                  ----                         -------
  Warning  ProvisioningFailed  3m54s (x26 over 10m)  persistentvolume-controller  no volume plugin matched name: kubernetes.io/no-provisioner
```
Is this a user error by wrong configuration, - or what does this mean?

Thank you for any advice

**Comment by bidluo** [comment]
You need to assign a provisioner to the PV or set a default cluster provisioner. This could be whatever your provider gives you, for example on digital ocean it's `do-block-storage` or if using NFS it's often `nfs-provisioner`.

**Comment by blecx** [comment]
Thank you for your answer. I did not know that

**Comment by Ark-kun** [comment]
>You need to assign a provisioner to the PV or set a default cluster provisioner. 

Can you please explain why? I though that `csi-rclone` allows abstracting over different cloud storages and allows same configuration to be deployed to different clouds (e.g. deploy Backblaze-backed csi-rclone to Amazon AWS or Google Cloud). Is this not correct?

**Comment by bidluo** [comment]
It does but it needs to know what to use to back it, each of these cloud providers provide their own underlying storage mechanism and not only that but you can choose which storage mechanism. For example if you want to use Longhorn or other NFS based storage you would set that as your provisioner. I imagine the issue OP was facing was that no provisioner was set so there was no backing storage which in turn caused the cluster to keep the volume in pending
