### ISSUE TITLE
 /bin/sh: no such file or directory

### ISSUE THREAD

**Issue by superbarne** [wunderio/csi-rclone#4]
Its looks like the image has no /bin/sh. 

I get following Error when i apply the kubernetes manifest:
```
failed - error: command '/bin/sh -c rm -rf /registration/csi-rclone /registration/csi-rclone-reg.sock' exited with 126: , message: "OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused \"exec: \\\"/bin/sh\\\": stat /bin/sh: no such file or directory\": unknown\r\n"
```

**Comment by superbarne** [comment]
Your previous commit (db2ca18dcec58d9389b4a325f6e13e9df5b42018) seems to work

**Comment by Jancis** [comment]
I think I made a booboo here
https://github.com/wunderio/csi-rclone/commit/bc0ed72f0789a5dac0c93272befdafccfe15203c#diff-71cdca121acd40fd7352f4657d4be85bR24
revert the line  24 back to `preStop` and run `kubectl apply` on that yaml file.
I'll push a code update meanwhile too.

**Comment by Jancis** [comment]
This should be fixed now with the https://github.com/wunderio/csi-rclone/commit/5178a61e2e562517feeb3970e81823018a709bfb
