### ISSUE TITLE
ARM images

### ISSUE THREAD

**Issue by stenwt** [wunderio/csi-rclone#8]
I attempted to run the CSI on K3S on Raspberry Pi 4s running an arm64 kernel, but all the images fail to start with "exec format error"; there are no arm64 or armv7 images available. Would appreciate if they were also supplied for these architectures.

**Comment by Jancis** [comment]
I am not familiar with multiarch builds, but I believe this should be solved now. I had nowhere to test if the plugin actually works, but I was able to launch the binary in emulated mode. 
If You ever get back to this and the mounts don't work (while pod starts), check kubelet path (https://github.com/wunderio/csi-rclone/issues/2#issuecomment-957567961)
Related commit: https://github.com/wunderio/csi-rclone/commit/cbe4ebb5ca359561c50cb648373250ef97794ce1
