### ISSUE TITLE
please release a new version to get the latest rclone binary

### ISSUE THREAD

**Issue by cameronbraid** [wunderio/csi-rclone#9]
Hi,

I am hitting a bug in csi-rclone 1.2.6 which uses rclone 1.48

```
docker run --rm -it --entrypoint rclone wunderio/csi-rclone:v1.2.6 version
rclone v1.48.0
```

The issue is an io error accessing 0 byte files, which is working in rclone 1.51 by testing a rclone mount locally

**Comment by stevefan1999-personal** [comment]
@Jancis can you roll out a new version by running the Dockerfile?

**Comment by hSATAC** [comment]
+1 to this.

Fixed it by rebuilding the docker image ourselves.

**Comment by Jancis** [comment]
Pushed v1.2.8 with rclone v1.53.1

> docker run --rm -it --entrypoint rclone wunderio/csi-rclone:v1.2.8 version
> rclone v1.53.1
> - os/arch: linux/amd64
> - go version: go1.15
